marttiphpbb_calendartableview_page_controller:
    pattern: /calendar/{year}/{month}/{day}
    defaults: { _controller: marttiphpbb.calendartableview.controller:page }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$
        day: ^[1-9]|[12][012]|3[01]$
