services:
    marttiphpbb.calendartableview.main_listener:
        class: marttiphpbb\calendartableview\event\main_listener
        tags:
            - { name: event.listener }

    marttiphpbb.calendartableview.viewing_listener:
        class: marttiphpbb\calendartableview\event\viewing_listener
        arguments:
            - '@controller.helper'
            - '%core.php_ext%'
            - '@language'
            - '@user'
        tags:
            - { name: event.listener }

    marttiphpbb.calendartableview.link_listener:
        class: marttiphpbb\calendartableview\event\link_listener
        arguments:
            - '@controller.helper'
        tags:
            - { name: event.listener }

    marttiphpbb.calendartableview.tag_listener:
        class: marttiphpbb\calendartableview\event\tag_listener
        arguments:
            - '@controller.helper'
            - '@marttiphpbb.calendartableview.store'
        tags:
            - { name: event.listener }

    marttiphpbb.calendartableview.menu_listener:
        class: marttiphpbb\calendartableview\event\menu_listener
        arguments:
            - '@controller.helper'
            - '@marttiphpbb.calendartableview.user_today'
            - '@auth'
        tags:
            - { name: event.listener }

    marttiphpbb.calendartableview.store:
        class: marttiphpbb\calendartableview\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.calendartableview.user_today:
        class: marttiphpbb\calendartableview\service\user_today
        arguments:
            - '@user'

    marttiphpbb.calendartableview.user_time:
        class: marttiphpbb\calendartableview\service\user_time
        arguments:
            - '@user'
            - '@marttiphpbb.calendartableview.store'

    marttiphpbb.calendartableview.controller:
        class: marttiphpbb\calendartableview\controller\main
        arguments:
            - '@dispatcher'
            - '@request'
            - '%core.php_ext%'
            - '@template'
            - '@language'
            - '@controller.helper'
            - '%core.root_path%'
            - '@marttiphpbb.calendartableview.pagination'
            - '@marttiphpbb.calendartableview.store'
            - '@marttiphpbb.calendartableview.user_today'
            - '@marttiphpbb.calendartableview.user_time'

    marttiphpbb.calendartableview.redirect_controller:
        class: marttiphpbb\calendartableview\controller\redirect
        arguments:
            - '@marttiphpbb.calendartableview.user_today'
            - '@controller.helper'

    marttiphpbb.calendartableview.pagination:
        class: marttiphpbb\calendartableview\service\pagination
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'
